# Generated by Django 6.1.1 on 2026-09-27 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('tipoEntrega', models.CharField(choices=[('DOMICILIO', 'Domicilio'), ('LOCAL', 'Local')], default='LOCAL', max_length=15)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PREPARACION', 'Preparación'), ('DESPACHO', 'Despacho'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=15)),
                ('fechaHoraEntregaEstimada', models.DateTimeField(blank=True, null=True)),
                ('total', models.IntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_realizados', to='usuarios.perfilcliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precioUnitario', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogo.plato')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='RutaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('zona', models.CharField(max_length=100)),
                ('repartidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_asignadas', to='usuarios.perfilrepartidor')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='ruta_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_ruta', to='pedidos.rutaentrega'),
        ),
    ]
