# Generated by Django 6.1.1 on 2026-10-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cuenta',
            constraint=models.CheckConstraint(condition=models.Q(('saldoDisponible__gte', 0)), name='saldo_no_negativo'),
        ),
    ]
