# Generated by Django 6.1.1 on 2026-10-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='plato',
            constraint=models.CheckConstraint(condition=models.Q(('precio__gte', 0)), name='precio_plato_no_negativo'),
        ),
    ]
