# Generated by Django 5.1.2 on 2026-10-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_plato_precio_plato_no_negativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='categoria',
            field=models.CharField(choices=[('platos', 'Platos y Entradas'), ('bebestibles', 'Bebestibles'), ('postres', 'Postres Variados'), ('extras', 'Extras y Salsas')], default='platos', max_length=20),
        ),
        migrations.AddField(
            model_name='plato',
            name='icono',
            field=models.CharField(blank=True, default='', help_text='Emoji representativo', max_length=10),
        ),
    ]
